name: Run Parasoft Jtest
trigger:
- master

pool:
  name: Default

steps:

# Configures your Gradle project.  
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    tasks: 'build jtest'
    options: '-Djtest.skip=true -I path\to\jtest\integration\gradle\init.gradle'

# Runs code analysis with Jtest.   
- task: RunParasoftJtest@0
  inputs:
    workingDir: '$(Build.Repository.LocalPath)'
    dataJson: 'build\jtest\jtest.data.json'

# Uploads analysis results in the SARIF format, so that they can be accessed in the 'Scans' tab.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/reports/report.sarif'
    ArtifactName: 'CodeAnalysisLogs'
    publishLocation: 'Container'

# Uploads all report files (.xml, .html, .sarif) as build artifacts.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/reports'
    ArtifactName: 'JtestReports'
    publishLocation: 'Container'