trigger:
- master

pool:
  name: Default

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
    options: '-Djtest.skip=true'
- task: Jtest@0
  name: jtest
  inputs:
    workingDir: '$(Build.Repository.LocalPath)'
    dataJson: 'demo.data.json'
- task: PublishPipelineArtifact@1
  displayName: 'SARIF Artifacts'
  inputs:
    targetPath: $(jtest.report)
    artifact: CodeAnalysisLogs