trigger:
- master

pool:
  name: Default

steps:
- task: CmdLine@2
  displayName: Checkout
  inputs:
    script: |
             git checkout $(Build.SourceBranchName)
             git pull
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    tasks: 'build jtest'
    options: '-Djtest.skip=true -I C:\Users\lukabass\jtest\integration\gradle\init.gradle'
    
- task: Jtest@0
  name: jtest
  inputs:
    workingDir: '$(Build.Repository.LocalPath)'
    dataJson: 'build\jtest\jtest.data.json'
    
- task: PublishParasoftResults@1
  inputs:
    resultsFiles: '$(jtest.report)'
    failOnFailures: false
    testRunTitle: 'Sample Test Run'